version: '2'
services:
  web:
    container_name: "devbox-elixir-postgres"
    build:
      context: .
      args:
        user: "${USER}"
    image: "devbox-elixir-postgres"
    volumes:
      - "~/.ssh/id_rsa:/home/${USER}/.ssh/id_rsa"
      - "~/.ssh/authorized_keys:/home/${USER}/.ssh/authorized_keys"
      - "~/devbox:/home/${USER}/mount"
    ports:
      - "22:22"
      - "80:80"
      - "3000:3000"
      - "4000:4000"
      - "8000:8000"
      - "8100:8100"
    depends_on:
      - postgres
  postgres:
    image: postgres
